# Generated by Django 3.2.1 on 2021-05-07 18:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A', max_length=200)),
                ('wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=200, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='0', max_length=200)),
                ('report_id', models.IntegerField(default=0)),
                ('date_worked', models.DateField(default=datetime.date.today)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=200, validators=[django.core.validators.MinValueValidator(0)])),
                ('job_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.jobgroup')),
            ],
            options={
                'ordering': ['employee_id', 'date_worked'],
            },
        ),
    ]
